name:                unscramble
version:             0.1.0.0
github:              "7h3w1zz/unscramble"
license:             BSD3
author:              "Jacob Collins"
maintainer:          "jaco3collins@gmail.com"
copyright:           "Jacob Collins"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/7h3w1zz/unscramble#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  unscramble-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - unscramble

tests:
  unscramble-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - unscramble
